TASK: Add missing repositories/distributionPackages configuration to composer
neos/flow-base-distribution pull request #9
Opened 2018-12-14 11:11 UTC by daniellienert

2018-12-14 13:53 UTC, mficzel approved these changes
Fine by reading and makes sense for flow-base-dist.

However i would consider reading this key blindly also an error and suggest to fix it there aswell.

2018-12-14 14:01 UTC, kdambekalns approved these changes

2018-12-14 14:02 UTC, kdambekalns commented on composer.json
> +        "distributionPackages": {
Wait… why give it a name at all? I never did that, so far.

2018-12-14 14:04 UTC, kdambekalns requested changes

2018-12-14 14:04 UTC, kdambekalns commented on composer.json
> +        "distributionPackages": {
Also, using JSON object notation (not an array) does not guarantee order. See https://getcomposer.org/doc/04-schema.md#repositories

2018-12-14 15:25 UTC, mficzel commented
@kdambekalns this is what we do aswell as in the neos-base-distribution. Works fine and naming things is not bad. Composer handles both fine and is also allowed by the spec. Also if you need an order between your local repositories you are in a situation where a single package is available via multiple repos. I would consider this very bad practice anyways.

2018-12-14 15:53 UTC, kdambekalns commented
Fine, but again:

> However, JSON key/value pairs are to be considered unordered so consistent behaviour cannot be guaranteed.

I'd not do this.

2018-12-15 12:52 UTC, daniellienert commented
Hey @kdambekalns, 
In fact that is how a `composer config distributionPackages path "./DistributionPackages/*"` would generate the config.
As @mficzel already mentioned, I just copied the lines from the Neos base distribution.
I am absolutely fine with the array variant, if you are against the object. But the Neos distribution should then be updated as well.

2018-12-19 16:20 UTC, kdambekalns commented
Wow, now that is stupid^Wweird–warning about order issues but creating an object when using the `config` command.

2019-01-02 21:16 UTC, merged

2019-07-16 08:49 UTC, tschoeki commented
This is still happening with a fresh install of Neos 4.3. Removing the repositories section as mentioned over here (https://discuss.neos.io/t/problem-with-neos-4-2-when-creating-new-package/3974/9) is still the "solution". Any suggestions on how to fix this?

2020-05-15 06:36 UTC, svparijs commented
I also ran into this issue on Neos 4.3 and 5.0. Any changes on how to fix this?